# AND (&) => IF BOTH BITS ARE 1 THEN ONLY RESULT IS 1 OTHERWISE 0
# OR (|) => IF ANY ONE BIT IS 1 THEN RESULT IS 1 OTHERWISE 0
# XOR (^) => IF BOTH BITS ARE DIFFERENT THEN RESULT IS 1 OTHERWISE 0
# NOT (~) => IT INVERTS THE BITS (0 TO 1 AND 1 TO 0)

a = 10
b = 3
print("AND OPERATOR:", a & b)
print("OR OPERATOR:", a | b)
print("XOR OPERATOR:", a ^ b)
print("NOT OPERATOR:", ~a)